/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dee0ff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#83e881",
        "on-secondary-fixed": "#3a0a00",
        "on-background": "#191c1e",
        "on-secondary-container": "#631800",
        "surface-tint": "#4355b9",
        "outline-variant": "#c5c5d4",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#852300",
        "tertiary-container": "#00691b",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        primary: "#24389c",
        "on-surface": "#191c1e",
        "on-error": "#ffffff",
        "tertiary-fixed": "#94f990",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e6",
        "inverse-on-surface": "#eff1f4",
        "on-surface-variant": "#454652",
        background: "#f7f9fc",
        "surface-container": "#eceef1",
        "surface-container-low": "#f2f4f7",
        "on-tertiary-fixed": "#002204",
        "surface-dim": "#d8dadd",
        "surface-container-high": "#e6e8eb",
        "primary-fixed-dim": "#bac3ff",
        "secondary-fixed": "#ffdbd0",
        "on-primary-container": "#cacfff",
        "surface-container-highest": "#e0e3e6",
        "inverse-primary": "#bac3ff",
        secondary: "#ac3509",
        tertiary: "#004e11",
        surface: "#f7f9fc",
        "secondary-fixed-dim": "#ffb59f",
        "on-tertiary-fixed-variant": "#005313",
        "on-primary-fixed-variant": "#293ca0",
        "secondary-container": "#fe6f42",
        "primary-container": "#3f51b5",
        "on-error-container": "#93000a",
        outline: "#757684",
        "on-primary-fixed": "#00105c",
        "surface-bright": "#f7f9fc",
        "tertiary-fixed-dim": "#78dc77",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        container_margin_mobile: "16px",
        sm: "8px",
        gutter: "16px",
        container_margin_desktop: "40px",
        xl: "32px",
        xs: "4px",
        md: "16px",
        lg: "24px",
        base: "8px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 4px 20px rgba(67, 85, 185, 0.04)",
        "card-hover": "0 8px 30px rgba(67, 85, 185, 0.08)",
        fab: "0 8px 24px rgba(67, 85, 185, 0.25)",
        nav: "0 -4px 20px rgba(67, 85, 185, 0.04)",
      },
    },
  },
  plugins: [],
};
