/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary": "var(--color-on-primary)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-background": "var(--color-on-background)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-tint": "var(--color-surface-tint)",
        "outline-variant": "var(--color-outline-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "tertiary-container": "var(--color-tertiary-container)",
        "error-container": "var(--color-error-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        primary: "var(--color-primary)",
        "on-surface": "var(--color-on-surface)",
        "on-error": "var(--color-on-error)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface-variant": "var(--color-surface-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        background: "var(--color-background)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-high": "var(--color-surface-container-high)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "inverse-primary": "var(--color-inverse-primary)",
        secondary: "var(--color-secondary)",
        tertiary: "var(--color-tertiary)",
        surface: "var(--color-surface)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-container": "var(--color-secondary-container)",
        "primary-container": "var(--color-primary-container)",
        "on-error-container": "var(--color-on-error-container)",
        outline: "var(--color-outline)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "surface-bright": "var(--color-surface-bright)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-secondary": "var(--color-on-secondary)",
        error: "var(--color-error)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        container_margin_mobile: "16px",
        sm: "8px",
        gutter: "16px",
        container_margin_desktop: "40px",
        xl: "32px",
        xs: "4px",
        md: "16px",
        lg: "24px",
        base: "8px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 4px 20px rgba(67, 85, 185, 0.04)",
        "card-hover": "0 8px 30px rgba(67, 85, 185, 0.08)",
        fab: "0 8px 24px rgba(67, 85, 185, 0.25)",
        nav: "0 -4px 20px rgba(67, 85, 185, 0.04)",
      },
    },
  },
  plugins: [],
};
